Repository encode/uvicorn, pull requests merged in 2020-12, with the labels that each got.

#871 Skip installation of signal handlers when not in main thread
  tests/middleware/test_trace_logging.py
  tests/test_default_headers.py
  tests/test_main.py
  tests/test_ssl.py
  uvicorn/server.py
Labels: enhancement

#875 Add --factory flag to support factory-style application imports
  docs/index.md
  docs/settings.md
  tests/test_auto_detection.py
  tests/test_config.py
  uvicorn/config.py
  uvicorn/main.py
Labels: enhancement

#878 Fix release date of 0.13.0
  CHANGELOG.md
Labels: docs

#876 Add tool to keep CLI usage in `index.md` in sync
  docs/deployment.md
  docs/index.md
  scripts/check
  scripts/lint
  tools/cli_usage.py
  uvicorn/main.py
Labels: tools library

#704 Fix failures when ASGI app rejects a connection during handshake
  uvicorn/protocols/websockets/websockets_impl.py
  uvicorn/protocols/websockets/wsproto_impl.py
Labels: bug

#884 Fix logger after scope removal
  uvicorn/logging.py
Labels: bug

#886 Log exception traceback in case of invalid HTTP request when using httptools
  uvicorn/protocols/http/httptools_impl.py
Labels: enhancement, http/httptools

#889 Log exception traceback in case of invalid HTTP request when using h11
  uvicorn/protocols/http/h11_impl.py
Labels: http/h11

#888 Add extra invalid HTTP request test cases
  tests/protocols/test_http.py
Labels: testing

#913 Fix lifespan tests
  tests/test_lifespan.py
Labels: testing

#914 Tweak detection of app factories
  tests/test_config.py
  uvicorn/config.py
Labels: bug

#917 Test suite refactor using async server context manager instead of background thread
  requirements.txt
  tests/middleware/test_trace_logging.py
  tests/protocols/test_websocket.py
  tests/test_default_headers.py
  tests/test_main.py
  tests/test_ssl.py
  tests/utils.py
Labels: refactor, testing

#923 Add docs script
  scripts/docs
Labels: tooling

#918 Remove requests dependency
  requirements.txt
  tests/client.py
  tests/middleware/test_debug.py
  tests/middleware/test_message_logger.py
  tests/middleware/test_proxy_headers.py
  tests/middleware/test_wsgi.py
  tests/test_client.py
Labels: refactor, testing
