Repository encode/uvicorn, pull requests merged in 2020-09, with the labels that each got.

#774 Make reload delay configurable
  uvicorn/config.py
  uvicorn/main.py
  uvicorn/supervisors/basereload.py
Labels: enhancement

#790 Move package editable install to requirements.txt
  requirements.txt
  scripts/install
Labels: refactor

#784 merge README.md updates into docs/index.md
  docs/index.md
Labels: docs
