Repository encode/uvicorn, pull requests merged in 2020-04, with the labels that each got.

#618 Cleanup fixes for watchdog reload
  setup.py
  uvicorn/supervisors/basereload.py
Labels: bug

#592 Add support for `forwarded-allow-ips` to gunicorn worker
  uvicorn/workers.py
Labels: enhancement

#621 Add flake8 to linters
  .travis.yml
  requirements.txt
  scripts/test
  setup.py
  tests/importer/raise_import_error.py
  tests/middleware/test_message_logger.py
  tests/middleware/test_wsgi.py
  tests/protocols/test_http.py
  tests/protocols/test_utils.py
  tests/protocols/test_websocket.py
  tests/supervisors/test_statreload.py
  tests/supervisors/test_watchdogreload.py
  tests/test_auto_detection.py
  tests/test_client.py
  uvicorn/importer.py
  uvicorn/loops/auto.py
  uvicorn/main.py
  uvicorn/protocols/http/auto.py
  uvicorn/protocols/http/h11_impl.py
  uvicorn/protocols/http/httptools_impl.py
  uvicorn/protocols/websockets/auto.py
  uvicorn/supervisors/statreload.py
Labels: tools library

#646 Reload when other files than py are changes, small test maintenance
  CHANGELOG.md
  tests/supervisors/__init__.py
  tests/supervisors/test_statreload.py
  tests/supervisors/test_watchgodreload.py
  uvicorn/supervisors/statreload.py
Labels: enhancement
