Repository encode/uvicorn, pull requests merged in 2021-06, with the labels that each got.

#929 Strict pytest
  setup.cfg
  tests/protocols/test_http.py
  tests/test_config.py
  tests/test_lifespan.py
  uvicorn/protocols/http/h11_impl.py
  uvicorn/protocols/http/httptools_impl.py
  uvicorn/protocols/websockets/websockets_impl.py
  uvicorn/protocols/websockets/wsproto_impl.py
Labels: testing, tooling

#818 Support disabling default Server and Date headers
  docs/deployment.md
  docs/index.md
  tests/test_default_headers.py
  uvicorn/config.py
  uvicorn/main.py
  uvicorn/server.py
Labels: enhancement

#1009 Adapt bind_socket to make it usable with multiple processes
  tests/test_config.py
  uvicorn/config.py
  uvicorn/main.py
Labels: enhancement, multiprocessing, uds, workers

#1077 Exit with status 3 when worker starts failed
  uvicorn/workers.py
Labels: hold
