Repository encode/uvicorn, pull requests merged in 2021-05, with the labels that each got.

#1034 Moved FlowControl class and globals to its own file in uvicorn/protocols/http/
  uvicorn/protocols/http/flow_control.py
  uvicorn/protocols/http/h11_impl.py
  uvicorn/protocols/http/httptools_impl.py
Labels: refactor

#1043 📝 Update markdown extensions to highlight code
  mkdocs.yml
Labels: docs

#1038 Change websockets version to v9
  setup.py
Labels: packaging

#1028 Update docs about reload_dirs
  docs/settings.md
Labels: docs

#980 tests: ignore coverage on helper test functions
  tests/supervisors/test_multiprocess.py
  tests/supervisors/test_reload.py
  tests/test_config.py
Labels: testing

#869 Switch to asyncio streams API
  uvicorn/_handlers/__init__.py
  uvicorn/_handlers/http.py
  uvicorn/protocols/http/h11_impl.py
  uvicorn/protocols/http/httptools_impl.py
  uvicorn/protocols/websockets/websockets_impl.py
  uvicorn/protocols/websockets/wsproto_impl.py
  uvicorn/server.py
Labels: refactor
