Repository encode/uvicorn, pull requests merged in 2022-06, with the labels that each got.

#1483 Add mypy coverage to `test_ssl` and `test_multiprocess`
  setup.cfg
  tests/supervisors/test_multiprocess.py
Labels: typing

#1525 Document how to run uvicorn programatically
  docs/index.md
Labels: docs

#1514 Allow configuring max_incomplete_event_size for h11 implementation
  docs/deployment.md
  docs/index.md
  docs/settings.md
  tests/protocols/test_http.py
  tests/test_cli.py
  uvicorn/config.py
  uvicorn/main.py
  uvicorn/protocols/http/h11_impl.py
Labels: waiting author
