Repository encode/uvicorn, pull requests merged in 2022-08, with the labels that each got.

#1598 Fix ASGI application on `test_multiprocess.py`
  tests/supervisors/test_multiprocess.py
Labels: testing

#1565 Fix uvicorn gunicorn worker class restarts when USR1 is issued
  uvicorn/workers.py
Labels: workers/gunicorn

#1605 typing: Config.forwarded_allow_ips can also be a list of strings
  uvicorn/config.py
  uvicorn/main.py
Labels: typing
