Repository encode/uvicorn, pull requests merged in 2022-07, with the labels that each got.

#1308 Add type hint to `websockets_impl.py`
  setup.cfg
  uvicorn/protocols/websockets/websockets_impl.py
Labels: typing

#1563 Drop httpx version to 0.23.0
  requirements.txt
Labels: dependencies, clean up

#1575 Add note about `--no-server-header` limitations when using WebSockets implementations
  docs/settings.md
Labels: docs
